const PRIORITY_CLASS = { high: 'bad', medium: 'warn', low: 'good' };
const CATEGORY_LABEL = {
  schema: 'Schema',
  content: 'Content',
  authority: 'Authority',
  competitive: 'Competitive',
  technical: 'Technical',
};

export default function Recommendations({ data }) {
  if (!data || !data.recommendations || data.recommendations.length === 0) {
    return (
      <div className="panel">
        <h2>Recommended Actions</h2>
        <div className="muted">
          No recommendations yet — they&apos;re generated by Claude at the end of each scan.
          Run a scan to populate this.
        </div>
      </div>
    );
  }

  return (
    <div className="panel">
      <h2>Recommended Actions</h2>
      {data.summary && (
        <p style={{ fontSize: 14, marginTop: 0, color: 'var(--text)' }}>{data.summary}</p>
      )}
      <ol style={{ paddingLeft: 18, margin: '12px 0 0' }}>
        {data.recommendations.map((r, i) => (
          <li key={i} style={{ marginBottom: 14 }}>
            <div style={{ display: 'flex', gap: 8, alignItems: 'center', flexWrap: 'wrap' }}>
              <span className={`pill ${PRIORITY_CLASS[r.priority] || 'muted'}`}>
                {r.priority || 'note'}
              </span>
              {r.category && (
                <span className="pill muted">{CATEGORY_LABEL[r.category] || r.category}</span>
              )}
              <strong style={{ fontSize: 14 }}>{r.title}</strong>
            </div>
            {r.why && (
              <div className="muted" style={{ fontSize: 13, marginTop: 4 }}>
                {r.why}
              </div>
            )}
            {r.action && (
              <div style={{ fontSize: 13, marginTop: 4 }}>
                <strong>Do:</strong> {r.action}
              </div>
            )}
          </li>
        ))}
      </ol>
      {data.gen_date && (
        <div className="muted" style={{ fontSize: 12, marginTop: 8 }}>
          Generated {data.gen_date}
        </div>
      )}
    </div>
  );
}
